apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  size: 500users
  ingress:
    enabled: true
    host: mattermost.mechatronica-pro
    annotations:
      kubernetes.io/ingress.class: nginx
  version: 9.3.0
  licenseSecret: 
  database:
    external:
      secret: chat-pg-secret
  fileStore:
    external:
      url: minio.mechatronica-pro
      bucket: chat-bucket
      secret: chat-s3-secret
