apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    targetRevision: 17.11.3
    helm:
      parameters:
        - name: volumePermissions.enabled
          value: 'true'
        - name: master.persistence.enabled
          value: 'true'
        - name: replica.persistence.enabled
          value: 'true'
        - name: global.storageClass
          value: local-storage
        - name: global.redis.password
          value: 'qUwTt8g9it'
        - name: master.persistence.existingClaim
          value: redis-pvc
        - name: pdb.create
          value: 'true'
        - name: replica.persistence.existingClaim
          value: redis-pvc
        - name: replica.replicaCount
          value: '1'
#        - name: master.resources.requests.memory
#          value: "256Mi"
#        - name: master.resources.requests.cpu
#          value: "0.5"
#        - name: master.resources.limits.memory
#          value: "256Mi"
#        - name: master.resources.limits.cpu
#          value: "0.5"
#        - name: replica.resources.requests.memory
#          value: "256Mi"
#        - name: replica.resources.requests.cpu
#          value: "0.5"
#        - name: replica.resources.limits.memory
#          value: "256Mi"
#        - name: replica.resources.limits.cpu
#          value: "0.5"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
