version: '3'
networks:
  mynetwork:
    external: true
services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    networks:
      - mynetwork
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:8.4.4-ubuntu
    container_name: grafana
    networks:
      - mynetwork
    ports:
      - "3000:3000"
