apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    host: minio.mechatronica-pro
    endpoint: http://gitlab-minio:9000
    path_style: true
    aws_access_key_id: admin 
    aws_secret_access_key: password
