apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  config: |
    s3:
      bucket: gitlab-registry-storage
      accesskey: admin
      secretkey: password
      region: us-east-1
      regionendpoint: "http://gitlab-minio:9000"
      v4auth: true
