---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    endpoint: 192.168.3.24:9000
    path_style: true
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin

---

apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  config: |
    s3: 
    bucket: gitlab-registry-storage
    accesskey: minioadmin
    secretkey: minioadmin
    region: us-east-1
    regionendpoint: 192.168.3.24:9000
    v4auth: true
