apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    endpoint: http://192.168.3.24:9000
    path_style: true
    aws_access_key_id: InakUlXpBjcyrGGlfiBM
    aws_secret_access_key: UliydKSDBWeDDPN8CoFaX1avs9fx01atX1ejhrAn
