apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    host: minio.mechatronica-pro
    endpoint: http://10.233.28.65:9000
    path_style: true
    aws_access_key_id: raBtepJuCjctEBPSNCNM
    aws_secret_access_key: YcdUZ6qy6XmPZnpnBqaz9CdBM9Mdu7TwGINxdip4
