apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  config: |
    s3:
      bucket: gitlab-registry-storage
      accesskey: InakUlXpBjcyrGGlfiBM
      secretkey: UliydKSDBWeDDPN8CoFaX1avs9fx01atX1ejhrAn
      region: us-east-1
      regionendpoint: "http://192.168.3.24:9000"
      v4auth: true
