apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  config: |
    access_key = MlfxHMLDPKndWSyvP0ECVkECkb3cFCD2gcN6wIuWD4qwm7Hn4l7hcrYl3aNSBzF3
    secret_key = ckM8mTuFrJoCvkC2ufKKTVpdZBhlUl2m5nmTUYsCK3iZfCKc8HRzpYcZL0cia5Ze
    bucket_location = us-east-1
    host_base = minio.mechatronica-pro
    host_bucket = minio.mechatronica-pro/%(bucket)
    default_mime_type = binary/octet-stream
    enable_multipart = True
    multipart_max_chunks = 10000
    multipart_chunk_size_mb = 128
    recursive = True
    recv_chunk = 65536
    send_chunk = 65536
    server_side_encryption = False
    signature_v2 = True
    socket_timeout = 300
    use_mime_magic = False
    verbosity = WARNING
    website_endpoint = http://minio.mechatronica-pro
