apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tiket-s8d/work_k8s'
    path: postgree
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
